// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230905003401_IdentityUserFix")]
    partial class IdentityUserFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.Task", b =>
                {
                    b.Property<Guid>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("TaskStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TaskID");

                    b.HasIndex("TaskStatusID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("webapi.Models.TaskStatus", b =>
                {
                    b.Property<Guid>("TaskStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TaskStatusName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("TaskStatusID");

                    b.ToTable("TaskStatus");

                    b.HasData(
                        new
                        {
                            TaskStatusID = new Guid("45617958-e263-459c-9ddb-d7a920792fdb"),
                            Created = new DateTime(2023, 9, 4, 19, 34, 1, 699, DateTimeKind.Utc).AddTicks(3787),
                            CreatedBy = "WebAPITask",
                            Modified = new DateTime(2023, 9, 4, 19, 34, 1, 699, DateTimeKind.Utc).AddTicks(3793),
                            ModifiedBy = "WebAPITask",
                            TaskStatusName = "Completada"
                        },
                        new
                        {
                            TaskStatusID = new Guid("e49795b0-cf64-4781-849f-c7c33d84f4d1"),
                            Created = new DateTime(2023, 9, 4, 19, 34, 1, 699, DateTimeKind.Utc).AddTicks(3795),
                            CreatedBy = "WebAPITask",
                            Modified = new DateTime(2023, 9, 4, 19, 34, 1, 699, DateTimeKind.Utc).AddTicks(3796),
                            ModifiedBy = "WebAPITask",
                            TaskStatusName = "No completada"
                        });
                });

            modelBuilder.Entity("webapi.Models.Task", b =>
                {
                    b.HasOne("webapi.Models.TaskStatus", "TaskStatus")
                        .WithMany()
                        .HasForeignKey("TaskStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
